back-end/airline_management/config/routes.rb
Rails.application.routes.draw do
  resources :flights
  resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

back-end/airline_management/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

back-end/airline_management/app/models/flight.rb
class Flight < ApplicationRecord
end

back-end/airline_management/app/models/user.rb
class User < ApplicationRecord
	def password=(val)
    	write_attribute(:password, val.reverse) #Para encriptar la contrasena, funcion basica guadar string en inversa
  	end
end

back-end/airline_management/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

back-end/airline_management/app/controllers/flights_controller.rb
class FlightsController < ApplicationController
  before_action :set_flight, only: [:show, :edit, :update, :destroy]
  skip_before_action :verify_authenticity_token

  # GET /flights
  # GET /flights.json
  def index
    @flights = Flight.all
  end

  # GET /flights/1
  # GET /flights/1.json
  def show
  end

  # GET /flights/new
  def new
    @flight = Flight.new
  end

  # GET /flights/1/edit
  def edit
  end

  # POST /flights
  # POST /flights.json
  def create
    @flight = Flight.new(flight_params)

    respond_to do |format|
      if @flight.save
        format.html { redirect_to @flight, notice: 'Flight was successfully created.' }
        format.json { render :show, status: :created, location: @flight }
      else
        format.html { render :new }
        format.json { render json: @flight.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /flights/1
  # PATCH/PUT /flights/1.json
  def update
    respond_to do |format|
      if @flight.update(flight_params)
        format.html { redirect_to @flight, notice: 'Flight was successfully updated.' }
        format.json { render :show, status: :ok, location: @flight }
      else
        format.html { render :edit }
        format.json { render json: @flight.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /flights/1
  # DELETE /flights/1.json
  def destroy
    @flight.destroy
    respond_to do |format|
      format.html { redirect_to flights_url, notice: 'Flight was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_flight
      @flight = Flight.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def flight_params
      params.permit(:id_flight, :from, :to, :date, :duration_hours, :price, :airplane_model, :time_departure, :time_arrival, :flight_distance)
    end
end

back-end/airline_management/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  skip_before_action :verify_authenticity_token

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.permit(:name, :last_name, :email, :password, :profile_picture, :id_flights, :record_kilometers)
    end
end

back-end/airline_management/app/helpers/application_helper.rb
module ApplicationHelper
end

back-end/airline_management/app/helpers/flights_helper.rb
module FlightsHelper
end

back-end/airline_management/app/helpers/users_helper.rb
module UsersHelper
end

back-end/airline_management/app/views/flights/_form.html.erb
<%= form_for(flight) do |f| %>
  <% if flight.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(flight.errors.count, "error") %> prohibited this flight from being saved:</h2>

      <ul>
      <% flight.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :id_flight %>
    <%= f.text_field :id_flight %>
  </div>

  <div class="field">
    <%= f.label :from %>
    <%= f.text_field :from %>
  </div>

  <div class="field">
    <%= f.label :to %>
    <%= f.text_field :to %>
  </div>

  <div class="field">
    <%= f.label :date %>
    <%= f.text_field :date %>
  </div>

  <div class="field">
    <%= f.label :duration_hours %>
    <%= f.number_field :duration_hours %>
  </div>

  <div class="field">
    <%= f.label :price %>
    <%= f.text_field :price %>
  </div>

  <div class="field">
    <%= f.label :airplane_model %>
    <%= f.text_field :airplane_model %>
  </div>

  <div class="field">
    <%= f.label :time_departure %>
    <%= f.text_field :time_departure %>
  </div>

  <div class="field">
    <%= f.label :time_arrival %>
    <%= f.text_field :time_arrival %>
  </div>

  <div class="field">
    <%= f.label :flight_distance %>
    <%= f.text_field :flight_distance %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

back-end/airline_management/app/views/flights/edit.html.erb
<h1>Editing Flight</h1>

<%= render 'form', flight: @flight %>

<%= link_to 'Show', @flight %> |
<%= link_to 'Back', flights_path %>

back-end/airline_management/app/views/flights/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Flights</h1>

<table>
  <thead>
    <tr>
      <th>Id flight</th>
      <th>From</th>
      <th>To</th>
      <th>Date</th>
      <th>Duration hours</th>
      <th>Price</th>
      <th>Airplane model</th>
      <th>Time departure</th>
      <th>Time arrival</th>
      <th>Flight distance</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @flights.each do |flight| %>
      <tr>
        <td><%= flight.id_flight %></td>
        <td><%= flight.from %></td>
        <td><%= flight.to %></td>
        <td><%= flight.date %></td>
        <td><%= flight.duration_hours %></td>
        <td><%= flight.price %></td>
        <td><%= flight.airplane_model %></td>
        <td><%= flight.time_departure %></td>
        <td><%= flight.time_arrival %></td>
        <td><%= flight.flight_distance %></td>
        <!-- <td><%= link_to 'Show', flight %></td>
        <td><%= link_to 'Edit', edit_flight_path(flight) %></td>
        <td><%= link_to 'Destroy', flight, method: :delete, data: { confirm: 'Are you sure?' } %></td>-->
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<!-- <%= link_to 'New Flight', new_flight_path %> -->

back-end/airline_management/app/views/flights/new.html.erb
<h1>New Flight</h1>

<%= render 'form', flight: @flight %>

<%= link_to 'Back', flights_path %>

back-end/airline_management/app/views/flights/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Id flight:</strong>
  <%= @flight.id_flight %>
</p>

<p>
  <strong>From:</strong>
  <%= @flight.from %>
</p>

<p>
  <strong>To:</strong>
  <%= @flight.to %>
</p>

<p>
  <strong>Date:</strong>
  <%= @flight.date %>
</p>

<p>
  <strong>Duration hours:</strong>
  <%= @flight.duration_hours %>
</p>

<p>
  <strong>Price:</strong>
  <%= @flight.price %>
</p>

<p>
  <strong>Airplane model:</strong>
  <%= @flight.airplane_model %>
</p>

<p>
  <strong>Time departure:</strong>
  <%= @flight.time_departure %>
</p>

<p>
  <strong>Time arrival:</strong>
  <%= @flight.time_arrival %>
</p>

<p>
  <strong>Flight distance:</strong>
  <%= @flight.flight_distance %>
</p>

<%= link_to 'Edit', edit_flight_path(@flight) %> |
<%= link_to 'Back', flights_path %>

back-end/airline_management/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AirlineManagement</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

back-end/airline_management/app/views/users/_form.html.erb
<%= form_for(user) do |f| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :last_name %>
    <%= f.text_field :last_name %>
  </div>

  <div class="field">
    <%= f.label :email %>
    <%= f.text_field :email %>
  </div>

  <div class="field">
    <%= f.label :password %>
    <%= f.text_field :password %>
  </div>

  <div class="field">
    <%= f.label :profile_picture %>
    <%= f.text_field :profile_picture %>
  </div>

  <div class="field">
    <%= f.label :id_flights %>
    <%= f.text_field :id_flights %>
  </div>

  <div class="field">
    <%= f.label :record_kilometers %>
    <%= f.number_field :record_kilometers %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

back-end/airline_management/app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

back-end/airline_management/app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Last name</th>
      <th>Email</th>
      <th>Password</th>
      <th>Profile picture</th>
      <th>Id flights</th>
      <th>Record kilometers</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.last_name %></td>
        <td><%= user.email %></td>
        <td><%= user.password %></td>
        <td><%= user.profile_picture %></td>
        <td><%= user.id_flights %></td>
        <td><%= user.record_kilometers %></td>
        <!-- <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td> -->
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<!-- <%= link_to 'New User', new_user_path %> -->

back-end/airline_management/app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

back-end/airline_management/app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @user.last_name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<p>
  <strong>Password:</strong>
  <%= @user.password %>
</p>

<p>
  <strong>Profile picture:</strong>
  <%= @user.profile_picture %>
</p>

<p>
  <strong>Id flights:</strong>
  <%= @user.id_flights %>
</p>

<p>
  <strong>Record kilometers:</strong>
  <%= @user.record_kilometers %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>  